# Generated by Django 5.1.7 on 2025-04-02 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meshping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='field',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='id',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='value',
        ),
        migrations.AddField(
            model_name='statistics',
            name='avg24h',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='statistics',
            name='avg5m',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='statistics',
            name='avg6h',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='statistics',
            name='last',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='statistics',
            name='lost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='statistics',
            name='max',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='statistics',
            name='min',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='statistics',
            name='recv',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='statistics',
            name='sent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='statistics',
            name='sum',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='target',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='meshping.target'),
        ),
    ]
