# Generated by Django 5.1.7 on 2025-04-04 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meshping', '0002_remove_statistics_field_remove_statistics_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistics',
            old_name='avg5m',
            new_name='avg15m',
        ),
    ]
