# Generated by Django 5.1.7 on 2025-04-05 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meshping", "0003_rename_avg5m_statistics_avg15m"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meta",
            name="field",
        ),
        migrations.RemoveField(
            model_name="meta",
            name="id",
        ),
        migrations.RemoveField(
            model_name="meta",
            name="value",
        ),
        migrations.AddField(
            model_name="meta",
            name="lkgt",
            field=models.JSONField(default=[], max_length=2048),
        ),
        migrations.AddField(
            model_name="meta",
            name="route_loop",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="meta",
            name="state",
            field=models.CharField(
                choices=[("up", "Up"), ("down", "Down"), ("unknown", "Unknown")],
                default="down",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="meta",
            name="traceroute",
            field=models.JSONField(default=[], max_length=2048),
        ),
        migrations.AlterField(
            model_name="meta",
            name="target",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="meshping.target",
            ),
        ),
        migrations.AlterField(
            model_name="statistics",
            name="min",
            field=models.FloatField(default=float("inf")),
        ),
    ]
