# Generated by Django 5.1.7 on 2025-04-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "meshping",
            "0004_remove_meta_field_remove_meta_id_remove_meta_value_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="meta",
            name="error",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="meta",
            name="state",
            field=models.CharField(
                choices=[
                    ("up", "Up"),
                    ("down", "Down"),
                    ("unknown", "Unknown"),
                    ("error", "Error"),
                ],
                default="down",
                max_length=10,
            ),
        ),
    ]
