# Generated by Django 5.1.7 on 2025-04-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meshping", "0005_meta_error_alter_meta_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meta",
            name="lkgt",
            field=models.JSONField(default=list, max_length=2048),
        ),
        migrations.AlterField(
            model_name="meta",
            name="traceroute",
            field=models.JSONField(default=list, max_length=2048),
        ),
    ]
