# Generated by Django 5.1.7 on 2025-04-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meshping", "0006_alter_meta_lkgt_alter_meta_traceroute"),
    ]

    operations = [
        migrations.AddField(
            model_name="meta",
            name="is_foreign",
            field=models.BooleanField(default=False),
        ),
    ]
