# Generated by Django 5.1.7 on 2025-04-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meshping", "0007_meta_is_foreign"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meta",
            name="state",
            field=models.CharField(
                choices=[
                    ("up", "Up"),
                    ("down", "Down"),
                    ("unknown", "Unknown"),
                    ("error", "Error"),
                ],
                default="unknown",
                max_length=10,
            ),
        ),
    ]
