---
kind: pipeline
name: default

steps:
- name: build docker image
  image: plugins/docker
  settings:
    repo: svedrin/meshping
    tags: latest
    username: svedrin
    password:
      from_secret: docker-registry-pw
    cache_from: "svedrin/meshping:latest"
  when:
    branch: master
    event:
      exclude:
      - pull_request
---
kind: signature
hmac: 3cecf8b3c3fd146ca46ef46398b0047482d220efac4d28fd897688078d8e4d9b

...
