kind: pipeline
name: default

steps:
- name: build docker image
  image: plugins/docker
  settings:
    repo: svedrin/meshping
    tags: latest
    username: svedrin
    password:
      from_secret: docker-registry-pw
    cache_from: "svedrin/meshping:latest"
  when:
    branch: master
    event:
      exclude:
      - pull_request
