---
kind: pipeline
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: pylint
  image: alpine:latest
  commands:
  - apk add --no-cache python3 py3-netifaces
  - pip3 install pylint pylint-fail-under
  - pip3 install -r requirements.txt
  - pylint-fail-under --fail_under 9 src/

- name: set "latest" tag
  image: alpine:latest
  commands:
  - echo -n "latest" > .tags
  when:
    branch: master

- name: set version tag
  image: alpine:latest
  commands:
  - echo -n ",${DRONE_TAG}" >> .tags
  when:
    branch: master
    event: tag

- name: build docker image
  image: plugins/docker
  settings:
    repo: svedrin/meshping
    username: svedrin
    password:
      from_secret: docker-registry-pw
    cache_from: "svedrin/meshping:latest"
  when:
    branch: master
    event:
      exclude:
      - pull_request

---
kind: pipeline
name: linux-arm

platform:
  arch: arm
  os: linux

steps:
- name: set "latest" tag
  image: alpine:latest
  commands:
  - echo -n "latest-armv7l" > .tags

- name: set version tag
  image: alpine:latest
  commands:
  - echo -n ",${DRONE_TAG}-armv7l" >> .tags
  when:
    event: tag

- name: build docker image
  image: plugins/docker
  settings:
    repo: svedrin/meshping
    username: svedrin
    password:
      from_secret: docker-registry-pw
    cache_from: "svedrin/meshping:latest-armv7l"

trigger:
  branch: master
  event:
    exclude:
    - pull_request

---
kind: pipeline
name: linux-arm64

platform:
  arch: aarch64
  os: linux

steps:
- name: set "latest" tag
  image: alpine:latest
  commands:
  - echo -n "latest-aarch64" > .tags

- name: set version tag
  image: alpine:latest
  commands:
  - echo -n ",${DRONE_TAG}-aarch64" >> .tags
  when:
    event: tag

- name: build docker image
  image: plugins/docker
  settings:
    repo: svedrin/meshping
    username: svedrin
    password:
      from_secret: docker-registry-pw
    cache_from: "svedrin/meshping:latest-aarch64"

trigger:
  branch: master
  event:
    exclude:
    - pull_request
---
kind: signature
hmac: 13a4c163afffa75cc3dc1dc193bbf68c51d6df95e81e9274bb8e2c738ca59edb

...
