---
kind: pipeline
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: pylint
  image: alpine:latest
  commands:
  - apk add --no-cache python3 py3-netifaces
  - pip3 install pylint pylint-fail-under
  - pip3 install -r requirements.txt
  - pylint-fail-under --fail_under 9 src/

- name: set "latest" tag
  image: alpine:latest
  commands:
  - echo -n "latest" > .tags
  when:
    branch: master

- name: set version tag
  image: alpine:latest
  commands:
  - echo -n ",${DRONE_TAG}" >> .tags
  when:
    branch: master
    event: tag

- name: build docker image
  image: plugins/docker
  settings:
    repo: svedrin/meshping
    username: svedrin
    password:
      from_secret: docker-registry-pw
    cache_from: "svedrin/meshping:latest"
  when:
    branch: master
    event:
      exclude:
      - pull_request

---
kind: pipeline
name: linux-arm

platform:
  arch: arm
  os: linux

steps:
- name: set "latest" tag
  image: alpine:latest
  commands:
  - echo -n "latest-armv7l" > .tags
  when:
    branch: master

- name: set version tag
  image: alpine:latest
  commands:
  - echo -n ",${DRONE_TAG}-armv7l" >> .tags
  when:
    branch: master
    event: tag

- name: build docker image
  image: plugins/docker
  settings:
    repo: svedrin/meshping
    username: svedrin
    password:
      from_secret: docker-registry-pw
    cache_from: "svedrin/meshping:latest-armv7l"
  when:
    branch: master
    event:
      exclude:
      - pull_request
---
kind: signature
hmac: 54a209269b80f3e40f73ec00c652b4d294f10ef631d49d5b16e696ba3240fa00

...
