---
kind: pipeline
name: tests

platform:
  arch: amd64
  os: linux

steps:
- name: meshping
  image: alpine:latest
  environment:
    MESHPING_DATABASE_PATH: /tmp
    MESHPING_PING_TIMEOUT:  1
    MESHPING_PING_INTERVAL: 2
    MESHPING_PEERING_INTERVAL: 10
    MESHPING_PEERS: "pylint-and-test:31337"
  commands:
  - apk add --no-cache python3 python3-dev py3-pip musl-dev liboping-dev make gcc bash dumb-init py3-netifaces py3-pillow ttf-dejavu
  - pip3 install Cython
  - pip3 install -r requirements.txt
  - echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories
  - apk add --no-cache py3-pandas
  - cd /drone/src/oping-py && python3 setup.py build && python3 setup.py install
  - cd /drone/src && dumb-init -- python3 src/meshping.py
  detach: true

- name: pylint-and-test
  image: alpine:latest
  commands:
  - apk add --no-cache python3 py3-pip py3-netifaces py3-pillow bash
  - pip3 install pylint pylint-fail-under
  - pip3 install -r requirements.txt
  - pip3 install -r features/requirements.txt
  - echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories
  - apk add --no-cache py3-pandas
  - bash -c "while ! nc -z meshping 9922; do sleep 1; done"
  - pylint-fail-under --fail_under 9 src/
  - python3 -m behave

---
kind: pipeline
name: linux-amd64-latest

platform:
  arch: amd64
  os: linux

steps:
- name: set "latest" tag
  image: alpine:latest
  commands:
  - echo -n "latest-amd64" > .tags
  when:
    branch: master

- name: set "staging" tag
  image: alpine:latest
  commands:
  - echo -n "staging-amd64" > .tags
  when:
    branch: staging

- name: set version tag
  image: alpine:latest
  commands:
  - echo -n ",${DRONE_TAG}-amd64" >> .tags
  when:
    branch: master
    event: tag

- name: build docker image
  image: plugins/docker
  settings:
    repo: svedrin/meshping
    username: svedrin
    password:
      from_secret: docker-registry-pw
    cache_from: "svedrin/meshping:latest-amd64"

trigger:
  branch:
  - master
  - staging
  event:
    exclude:
    - pull_request

depends_on:
- tests

---
kind: pipeline
name: linux-armv7l-latest

platform:
  arch: arm
  os: linux

steps:
- name: set "latest" tag
  image: alpine:latest
  commands:
  - echo -n "latest-armv7l" > .tags
  when:
    branch: master

- name: set "staging" tag
  image: alpine:latest
  commands:
  - echo -n "staging-armv7l" > .tags
  when:
    branch: staging

- name: set version tag
  image: alpine:latest
  commands:
  - echo -n ",${DRONE_TAG}-armv7l" >> .tags
  when:
    branch: master
    event: tag

- name: build docker image
  image: plugins/docker
  settings:
    repo: svedrin/meshping
    username: svedrin
    password:
      from_secret: docker-registry-pw
    cache_from: "svedrin/meshping:latest-armv7l"

trigger:
  branch:
  - master
  - staging
  event:
    exclude:
    - pull_request

depends_on:
- tests


---
kind: pipeline
type: docker
name: manifest

steps:
- name: publish
  image: plugins/manifest:1.2
  settings:
    ignore_missing: true
    spec: docker-manifest-latest.tmpl
    username: svedrin
    password:
      from_secret: docker-registry-pw

trigger:
  branch:
  - master
  - staging
  event:
    exclude:
    - pull_request

depends_on:
- linux-amd64-latest
- linux-armv7l-latest


---
kind: signature
hmac: 4b1de4f46660dbb0e63e5e5aecdf28a1a7b6d4a973118c9d87047d35f8d2faa5

...
