---
kind: pipeline
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: set "latest" tag
  image: alpine:latest
  commands:
  - echo -n "latest" > .tags
  when:
    branch: master
    event: tag

- name: set version tag
  image: alpine:latest
  commands:
  - echo -n ",${DRONE_TAG}" >> .tags
  when:
    branch: master
    event: tag

- name: build docker image
  image: plugins/docker
  settings:
    repo: svedrin/meshping
    username: svedrin
    password:
      from_secret: docker-registry-pw
    cache_from: "svedrin/meshping:latest"
  when:
    branch: master
    event:
      exclude:
      - pull_request

---
kind: pipeline
name: linux-arm

platform:
  arch: arm
  os: linux

steps:
- name: set "latest" tag
  image: alpine:latest
  commands:
  - echo -n "latest-armv7l" > .tags
  when:
    branch: master
    event: tag

- name: set version tag
  image: alpine:latest
  commands:
  - echo -n ",${DRONE_TAG}-armv7l" >> .tags
  when:
    branch: master
    event: tag

- name: build docker image
  image: plugins/docker
  settings:
    repo: svedrin/meshping
    username: svedrin
    password:
      from_secret: docker-registry-pw
    cache_from: "svedrin/meshping:latest-armv7l"
  when:
    branch: master
    event:
      exclude:
      - pull_request
---
kind: signature
hmac: 0d2a68a49b47ac39ac669af9e25ad5b5f29731c27d823fbd268c026fff04212e

...
