kind: pipeline
name: default

steps:
- name: build docker image
  image: plugins/docker
  settings:
    repo: docker.funzt-halt.net/meshping
    tags: latest
    cache_from: "docker.funzt-halt.net/meshping:latest"
