@startuml

title Network Map

node "{[ hostname ]}" as SELF

{% for (lft, rgt) in uniq_links -%}
"{[ lft ]}" -- "{[ rgt ]}"
{% endfor -%}

footer rendered with PlantUML and [[http://github.com/Svedrin/meshping Meshping]]
@enduml
