version: '2'

services:
  meshping:
    # for x86_64 and amd64:
    # image: "svedrin/meshping:latest"
    # for raspberry Pi 3 or other ARMv7-based things (see `uname -m`):
    image: "svedrin/meshping:latest-armv7l"
    network_mode: "host"
    restart: always
    volumes:
      - "meshping-data:/opt/meshping/db"
    labels:
      "com.centurylinklabs.watchtower.enable": "true"
    # If you want to add other Meshping instances to peer with, uncomment this:
    #environment:
    #  MESHPING_PEERS: 10.10.10.1:9922,10.10.20.1:9922

  watchtower:
    image: "containrrr/watchtower:latest"
    command: "--label-enable --cleanup --debug --interval 60"
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
