{
 "title": "Meshping overview",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "target",
    "query": "label_values(meshping_min,target)"
   },
   {
    "name": "interval",
    "query": "5s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "name",
    "query": "label_values(meshping_min,name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Average ping",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(meshping_pings_sum{target=~\"$target\",name=~\"$name\"}[$interval])  \n  /\r\n  rate(meshping_pings_count{target=~\"$target\",name=~\"$name\"}[$interval])\n) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sent/received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(meshping_sent{target=~\"$target\",name=~\"$name\"}[$interval])) by (name, target)",
     "legendFormat": "{{name}}: {{target}} sent"
    },
    {
     "expr": "sum(increase(meshping_recv{target=~\"$target\",name=~\"$name\"}[$interval])) by (name, target)",
     "legendFormat": "{{name}}: {{target}} recv"
    }
   ]
  },
  {
   "title": "Packet loss",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(meshping_lost{target=~\"$target\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: {{target}}"
    }
   ]
  }
 ]
}