when:
  - event: push
    branch:
      include: [master, staging]
  - event: tag

labels:
  arch: amd64

depends_on: [build-arm32]

steps:
  - name: build latest
    image: woodpeckerci/plugin-docker-buildx
    privileged: true
    settings:
      username: svedrin
      password:
        from_secret: docker-registry-pw
      repo: svedrin/meshping
      tags: latest-arm64
      platforms: linux/arm64
    when:
      - event: push
        branch: master

  - name: build staging
    image: woodpeckerci/plugin-docker-buildx
    privileged: true
    settings:
      username: svedrin
      password:
        from_secret: docker-registry-pw
      repo: svedrin/meshping
      tags: staging-arm64
      platforms: linux/arm64
    when:
      - event: push
        branch: staging

  - name: build tagged
    image: woodpeckerci/plugin-docker-buildx
    privileged: true
    settings:
      username: svedrin
      password:
        from_secret: docker-registry-pw
      repo: svedrin/meshping
      tags: ${CI_COMMIT_TAG}-arm64
      platforms: linux/arm64
    when:
      - event: tag
