when:
  - event: push
    branch:
      include: [master, staging]
  - event: tag

labels:
  arch: amd64

steps:
  - name: pylint-and-test
    image: alpine:3.20
    environment:
      MESHPING_DATABASE_PATH: /tmp
      MESHPING_PING_TIMEOUT: "1"
      MESHPING_PING_INTERVAL: "2"
      MESHPING_PEERING_INTERVAL: "10"
      MESHPING_PEERS: "localhost:31337"
    commands:
      - apk add --no-cache python3 python3-dev py3-pip musl-dev liboping-dev make gcc bash dumb-init py3-netifaces py3-pillow ttf-dejavu py3-pandas cython tzdata
      - pip3 install --break-system-packages -r requirements.txt
      - pip3 install --break-system-packages -r features/requirements.txt
      - pip install --break-system-packages --no-build-isolation --no-cache-dir oping-py/
      - pip3 install --break-system-packages pylint
      - dumb-init -- python3 src/meshping.py &
      - while ! nc -z localhost 9922; do sleep 1; done
      - pylint --fail-under 9 src/
      - python3 -m behave
